### ISSUE TITLE
Where can I find the command line application?

### ISSUE THREAD

**Issue by holger1414** [zivillian/ora2mqtt#12]
Hello!

I would like to try your development, but documentation is difficult to follow :)
Where is the command line application that is mentioned.

Thank you very much for help!

**Comment by gratefulUser1** [comment]
You can find and download the binaries from the [releases](https://github.com/zivillian/ora2mqtt/releases) section. Otherwise you need to clone the repo and build the binaries yourself.

**Comment by holger1414** [comment]
Thank you!
I will try it out :)

**Comment by holger1414** [comment]
More questions, if you don't mind :)
You state: "The certificate is stored locally on the device and can be read when the flag has been set.android:debuggable"

How do I do that?

**Comment by gratefulUser1** [comment]
You don't need to when you only want to use the application.

holger1414 ***@***.***> schrieb am So., 5. Mai 2024, 16:04:

**Comment by holger1414** [comment]
My aim is to integrate Ora data to Home assistant.
As I understand it, your command line application needs to poll the cloud
service and needs certs.

I have large setup and have been able to integrate quite a lot, but this
one is hard :)

Thank you for your patience!


Kontakt GratefulUser1 ***@***.***>) kirjutas kuupäeval E, 6.
mai 2024 kell 08:55:

**Comment by gratefulUser1** [comment]
Which operating system do you intend to use? Here is the general basic
steps you need to take:

1. Make sure you have an account for the Ora App on your mobile device.
2. Download the binaries for the ora2mqtt app.
3. Run the 'ora2mqtt(.exe) -configure' command from the binaries.
4. Input your credentials from the account (and MQTT server if applicable).
The configure command should complete successfully (you need to input a PIN
which you receive on the email address of your account).

5.
On windows: Now simply run the 'ora2mqtt.exe -i 30 -run' command.

The app will disconnect after a while (hours/days). You should wrap it in a
batch file on windows to restart after every disconnect as a workaround for
now.

On Linux: Follow the steps described in the README.md of this repo.



holger1414 ***@***.***> schrieb am Mo., 6. Mai 2024, 08:07:

**Comment by holger1414** [comment]
Thank you for the steps!

I downloaded the
https://github.com/zivillian/ora2mqtt/releases/download/v0.0.1/ora2mqtt-win-x64.zip
Extracted everything and tried the command in administrator command prompt.
I get the following error:

==============
C:\Users\Holger\Downloads\ora2mqtt-win-x64>ora2mqtt.exe -configure
config file (onfigure) missing
==============

Now what?

(I sent some beer/coffe money your way!! :)

Kontakt GratefulUser1 ***@***.***>) kirjutas kuupäeval E, 6.
mai 2024 kell 14:05:

**Comment by gratefulUser1** [comment]
Try 'ora2mqtt.exe configure'. Just omit the dash. Same for the 'run'
command.

holger1414 ***@***.***> schrieb am Mo., 6. Mai 2024, 16:30:

**Comment by gratefulUser1** [comment]
BTW: I am not the author of this software. But I fully agree you should send him some :coffee: :beers: :)

**Comment by holger1414** [comment]
Configuration successful!
However, I see no relevant traffic in mMQTT Explorer.
What might be the problem now?

It connects to the broker.

2024-05-06 18:13:35: New client connected from 192.168.1.66:49965 as
0650ede2164048b8a95d2c231c7ef984 (p2, c1, k15, u'MQTTmaakler').
2024-05-06 18:14:13: Client 0650ede2164048b8a95d2c231c7ef984 closed
its connection.



Kontakt GratefulUser1 ***@***.***>) kirjutas kuupäeval E, 6.
mai 2024 kell 17:44:

**Comment by gratefulUser1** [comment]
I assume it's something in the configuration of your MQTT broker. Try to
listen to GWM/# an try to play around with your config. Hard to tell from
remote.

holger1414 ***@***.***> schrieb am Mo., 6. Mai 2024, 17:19:

**Comment by gratefulUser1** [comment]
In case you can run the app with the 'ora2mqtt run' command and it does not
yield an error, I think it has to be related to your MQTT broker/config. Is
the user you sign in allowed to publish on the GWM/ root topic?

holger1414 ***@***.***> schrieb am Mo., 6. Mai 2024, 19:19:

**Comment by holger1414** [comment]
Tested with several admin logins. No luck :(

Kontakt GratefulUser1 ***@***.***>) kirjutas kuupäeval E, 6.
mai 2024 kell 23:28:

**Comment by zivillian** [comment]
> All I can think of, is my app is for baltic market and can not get anything from DE or UK servers.

This is something I can try to look into:
- Which App are you using? This is all based on the com.ora.**germany** app.
- Which country have you selected for your account?
- Would you be able to share your car with me?

**Comment by holger1414** [comment]
Hi!

I am using "My GWM" app.
My GWM – Rakendused Google Plays
<https://play.google.com/store/apps/details?id=com.gwm.eu>
Developer is Great Wall Motor Deutschland GmbH, so probably/hopefully using
the same "framework". As mentioned earlier, command line app config is
successfully created.
I tried both DE and UK.

As I am very interested in successful integration I would share my car
gladly, but could you explain your action plan?

Thank you for not giving up!! :D

Kontakt zivillian ***@***.***>) kirjutas kuupäeval T, 28.
mai 2024 kell 20:18:

**Comment by peerapon01** [comment]
@holger1414 @zivillian maybe you can try changing region in subdomain in H5HttpClientName and AppHttpClientName and all others mentioned about base url. (eu-xx-gateway) 
For my case. I'm using My GWM app in Thailand. it need to be `ap-xx-gateway` to make this working.

you can try to monitoring the app url by simply proxy the request. only getting corrent subdomain is enough

**Comment by peerapon01** [comment]
@holger1414 @zivillian maybe you can try changing region in subdomain in [H5HttpClientName](https://github.com/zivillian/ora2mqtt/blob/main/libgwmapi/GwmApiClient.cs) and [AppHttpClientName](https://github.com/zivillian/ora2mqtt/blob/main/libgwmapi/GwmApiClient.cs) and all other place that mentioned about base url. (eu-xx-gateway) 
For my case. I'm using My GWM app in Asia. it need to be `ap-h5-gateway` and `ap-app-gateway` to make this working.

you can try to monitoring the app url by simply proxy the request. only getting corrent subdomain is enough

**Comment by zivillian** [comment]
I've found and analyzed the com.gwm.eu app and it also contains a list of endpoints, but as far as I can tell the app is also using the `eu-app-gateway` and `eu-h5-gateway` endpoints.

@peerapon01 do you want to use this project in asia and need the URL to be part of the config? If so it would be great if you could create a separate issue. This change shouldn't be too complicated.

**Comment by holger1414** [comment]
Configuration again successful.
[image: image.png]
After run I see these lines in Broker log:

2024-05-29 21:35:41: New client connected from 192.168.1.239:53218 as
e3ffdaf6e8504fa296516c0cd104f341 (p2, c1, k15, u'gwm').


Broker account must be alright, as I can log in with the same credentials
using MQTTexplorer and publish gwm/test

[image: image.png]



Kontakt zivillian ***@***.***>) kirjutas kuupäeval K, 29.
mai 2024 kell 21:08:

**Comment by zivillian** [comment]
do you get any error message from ora2mwtt?

**Comment by holger1414** [comment]
Only output is after ctrl-C, but this probably is not relevant.

C:\Users\vagak\Downloads\ora2mqtt-win-x64>ora2mqtt.exe run
System.OperationCanceledException: The operation was canceled.
   at System.Threading.PeriodicTimer.State.Signal(Boolean stopping, CancellationToken cancellationToken)
   at System.Threading.PeriodicTimer.State.<>c.<WaitForNextTickAsync>b__6_0(Object state, CancellationToken cancellationToken)
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.Cancel()
   at Program.<>c__DisplayClass0_0.<<Main>$>b__0(Object s, ConsoleCancelEventArgs e) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/Program.cs:line 17
   at System.Console.HandlePosixSignal(PosixSignalContext ctx)
   at System.Runtime.InteropServices.PosixSignalRegistration.HandlerRoutine(Int32 dwCtrlType)
--- End of stack trace from previous location ---
   at System.Threading.PeriodicTimer.State.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at ora2mqtt.RunCommand.Run(CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/RunCommand.cs:line 43
   at Program.<Main>$(String[] args) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/Program.cs:line 23

**Comment by zivillian** [comment]
Thanks for testing - I'll add a debug switch (but it may take a few days). It would be great if you could then test again.

**Comment by holger1414** [comment]
Great! Will do.

**Comment by zivillian** [comment]
I've added a debug switch (`ora2mqtt run -d`) and build [new binaries](https://github.com/zivillian/ora2mqtt/actions/runs/9307022638#artifacts) - can you test again?
Please be aware that it will log a lot of details including sensitive data - so please check twice before uploading you log.

**Comment by holger1414** [comment]
Let it run for a minute.
Log was longer, but content was repeating.
I am posting the beginning with stripped sensitive info.

`C:\Users\vagak\Downloads\ora2mqtt-win-x64>ora2mqtt run -d
dbug: ora2mqtt.Logging.MqttLogger[0]
      Trying to connect with server '192.168.1.113:1883'
dbug: ora2mqtt.Logging.MqttLogger[0]
      Connection with server established
dbug: ora2mqtt.Logging.MqttLogger[0]
      TX (56 bytes) >>> Connect: [ClientId=-del-] [Username=gwm] [Password=****] [KeepAlivePeriod=15] [CleanSession=True]
dbug: ora2mqtt.Logging.MqttLogger[0]
      RX (4 bytes) <<< ConnAck: [ReturnCode=ConnectionAccepted] [ReasonCode=Success] [IsSessionPresent=False]
dbug: ora2mqtt.Logging.MqttLogger[0]
      Authenticated MQTT connection with server established.
info: ora2mqtt.Logging.MqttLogger[0]
      Connected
dbug: ora2mqtt.Logging.MqttLogger[0]
      Start receiving packets.
dbug: ora2mqtt.Logging.MqttLogger[0]
      Start sending keep alive packets.
info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-h5-gateway.gwmcloud.com/app-api/api/v1.0/user/getUserBaseInfo
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      language: en
      systemType: 1
      country: EE
      accessToken: 

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 351.1021ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      Date: Thu, 30 May 2024 18:40:33 GMT
      Connection: keep-alive
      X-Response-Default-Foo: Default-Bar
      Content-Type: application/json; charset=UTF-8
      Content-Length: 499

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-app-gateway.gwmcloud.com/app-api/api/v1.0/vehicle/acquireVehicles
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 288.6942ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      X-Response-Default-Foo: Default-Bar
      Date: Thu, 30 May 2024 18:40:33 GMT
      Content-Type: application/json
      Content-Length: 51

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-h5-gateway.gwmcloud.com/app-api/api/v1.0/user/getUserBaseInfo
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      language: en
      systemType: 1
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 180.4725ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      Date: Thu, 30 May 2024 18:40:43 GMT
      Connection: keep-alive
      X-Response-Default-Foo: Default-Bar
      Content-Type: application/json; charset=UTF-8
      Content-Length: 499

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-app-gateway.gwmcloud.com/app-api/api/v1.0/vehicle/acquireVehicles
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 151.7023ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      X-Response-Default-Foo: Default-Bar
      Date: Thu, 30 May 2024 18:40:43 GMT
      Content-Type: application/json
      Content-Length: 51

dbug: ora2mqtt.Logging.MqttLogger[0]
      TX (2 bytes) >>> PingReq
dbug: ora2mqtt.Logging.MqttLogger[0]
      RX (2 bytes) <<< PingResp
info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-h5-gateway.gwmcloud.com/app-api/api/v1.0/user/getUserBaseInfo
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      language: en
      systemType: 1
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 167.7036ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      Date: Thu, 30 May 2024 18:40:53 GMT
      Connection: keep-alive
      X-Response-Default-Foo: Default-Bar
      Content-Type: application/json; charset=UTF-8
      Content-Length: 499

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-app-gateway.gwmcloud.com/app-api/api/v1.0/vehicle/acquireVehicles
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 148.2003ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      X-Response-Default-Foo: Default-Bar
      Date: Thu, 30 May 2024 18:40:53 GMT
      Content-Type: application/json
      Content-Length: 51

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-h5-gateway.gwmcloud.com/app-api/api/v1.0/user/getUserBaseInfo
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      language: en
      systemType: 1
      country: EE
      accessToken=-del-

dbug: ora2mqtt.Logging.MqttLogger[0]
      TX (2 bytes) >>> PingReq
dbug: ora2mqtt.Logging.MqttLogger[0]
      RX (2 bytes) <<< PingResp
info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 157.5298ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      Date: Thu, 30 May 2024 18:41:03 GMT
      Connection: keep-alive
      X-Response-Default-Foo: Default-Bar
      Content-Type: application/json; charset=UTF-8
      Content-Length: 499

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-app-gateway.gwmcloud.com/app-api/api/v1.0/vehicle/acquireVehicles
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 202.9082ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      X-Response-Default-Foo: Default-Bar
      Date: Thu, 30 May 2024 18:41:03 GMT
      Content-Type: application/json
      Content-Length: 51

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-h5-gateway.gwmcloud.com/app-api/api/v1.0/user/getUserBaseInfo
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      language: en
      systemType: 1
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 164.3416ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      Date: Thu, 30 May 2024 18:41:13 GMT
      Connection: keep-alive
      X-Response-Default-Foo: Default-Bar
      Content-Type: application/json; charset=UTF-8
      Content-Length: 499

info: System.Net.Http.HttpClient[100]
      Sending HTTP request GET https://eu-app-gateway.gwmcloud.com/app-api/api/v1.0/vehicle/acquireVehicles
trce: System.Net.Http.HttpClient[102]
      Request Headers:
      rs: 2
      terminal: GW_APP_ORA
      brand: 3
      country: EE
      accessToken=-del-

info: System.Net.Http.HttpClient[101]
      Received HTTP response headers after 157.0231ms - 200
trce: System.Net.Http.HttpClient[103]
      Response Headers:
      X-Response-Default-Foo: Default-Bar
      Date: Thu, 30 May 2024 18:41:13 GMT
      Content-Type: application/json
      Content-Length: 51

`

**Comment by zivillian** [comment]
this looks like we also need to log the response body (at least for `getUserBaseInfo` and `acquireVehicles`)

**Comment by holger1414** [comment]
Yes, I agree.

**Comment by zivillian** [comment]
I've looked at your log again and I can see no error. Are you sure, that your car is registered or shared with the account you are using? If you don't get any mqtt message this would mean there is no vahicle in your account.

**Comment by zivillian** [comment]
I've added the responses to the log output - can you test again with the [new binaries](https://github.com/zivillian/ora2mqtt/actions/runs/10332649136#artifacts)?

**Comment by holger1414** [comment]
It is already working very well!
I tried again after your recent update (GWM backend update) expecting the
same result, but everything started woking.
I would say, that I did everything exactly as before. :)

Thank you!
Lets hope they will not break things too often ;)

Kontakt zivillian ***@***.***>) kirjutas kuupäeval L, 10.
august 2024 kell 18:29:

**Comment by zivillian** [comment]
That's great!
