### ISSUE TITLE
gwm telematic codes

### ISSUE THREAD

**Issue by ipsBruno** [zivillian/ora2mqtt#16]
I found a complete mapping of the messages and their respective codes from Ora.

https://gist.github.com/bossoq/194a40fc239a7428a3e539e4e382d941

**Comment by zivillian** [comment]
Thanks! I've added the information to #3

**Comment by Jens-Wymeersch** [comment]
@ipsBruno I am trying to figure out if there is a code for the charger power (in kw). Or a state of the ORA in KWh (instead of percentage of kms).

**Comment by holger1414** [comment]
There is no code for charger power. Consider using energy meter connected to your charger.
To find the state of the battery in kWh use this calculation: https://github.com/zivillian/ora2mqtt/issues/28#issuecomment-2539367210
