### ISSUE TITLE
Is there any risc of rate limiting?

### ISSUE THREAD

**Issue by holger1414** [zivillian/ora2mqtt#25]
Hi!

I see these lines in Docker log periodically.
![image](https://github.com/user-attachments/assets/94562a3f-8632-434c-81c2-2f0f1fdffc72)

Container restarts succesfully.
Is that important or can be ingnored?

Thank you!

**Comment by zivillian** [comment]
you have 6 hours between thos two ocurrences - so I'd say it's not rate limiting. But we should look into the details - I'll try to also log the response body if  there is an error response from the api.
