### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by Jens-Wymeersch** [zivillian/ora2mqtt#27]
Sorry for my ignorance, but I'm trying to figure out how to spin up a docker for this project. You indicate `Die config muss vorher mit ora2mqtt configure erstellt werden`. Unclear how to do this ? 

I guess after I get through this step, i get ora2mqtt.yml file and run following command 

`docker run -d --restart=unless-stopped -v ./ora2mqtt.yml:/config/ora2mqtt.yml zivillian/ora2mqtt:latest`

**Comment by zivillian** [comment]
It's currently not possible to create the config using docker. You need to download the [binaries from the release](https://github.com/zivillian/ora2mqtt/releases) and run
```bash
./ora2mqtt configure
```
