### ISSUE TITLE
Vorklimatisierung auch während Ladegestecker drin?

### ISSUE THREAD

**Issue by fl034** [zivillian/ora2mqtt#4]
Moin,
die ORA App zeigt ja eine Fehlermeldung, wen man das Auto vorzuheizen möchte während die "Ladepistole" eingesteckt ist.
Wäre es dir möglich, den API request mal nachzustellen, um zu sehen, ob die Fehlermeldung ggf. nur im Client stattfindet und man das Problem per API umgehen kann?
LG

**Comment by zivillian** [comment]
Ich bin mir relativ sicher, dass die Fehlermeldung nicht aus der App kommt, aber ich prüfe das nochmal nach.

**Comment by zivillian** [comment]
Ich hab mir das angeschaut und wie vermutet kommt die Fehlermeldung direkt aus der API zurück:
```json
{
    "code": "000000",
    "data": [
        {
            "anticipationCode": null,
            "commandType": null,
            "hwCommandId": "df3b6dda-6dd2-4bea-a8f1-2fa3b72b02ff",
            "hwResult": 128,
            "remoteType": "0x04",
            "resultCode": "13",
            "resultMsg": "Bitte stellen Sie sicher, dass das Stromsystem ausgeschaltet ist, alle Türen geschlossen und verriegelt sind, der Kraftstoff-/Batteriestand ausreichend ist und die Ladepistole nicht angeschlossen ist",
            "vehicleId": 1234567890123456789
        }
    ],
    "description": "SUCCESS"
}
```
