### ISSUE TITLE
Meldung "Refresh Token has expired"

### ISSUE THREAD

**Issue by nicpear** [zivillian/ora2mqtt#5]
Hallo,
ich bekomme nach der erfolgreichen Konfiguration beim Start immer die Meldung "Refresh Token has expired".
Ich habe bereits einen zweiten Ora-Account dafür erstellt und das Fahrzeug geteilt. Hast du eine Idee, woran es liegt?

**Comment by zivillian** [comment]
Ich muss gestehen, dass ich das Projekt in letzten Monaten nicht weiterverfolgt habe - aktuell läuft das noch nicht einmal für mein eigenes Auto. Daher habe ich keine Ahnung was genau das Problem ist - ich kann mir aber durchaus vorstellen, dass ORA was an der API geändert hat.

Ich hoffe ich finde in den nächsten Monaten wieder etwas Zeit...

**Comment by zivillian** [comment]
ich habe die Ursache gefunden: der Endpunkt um die Liste der Fahrzeuge auszulesen benötigt jetzt zusätzlich den Header `country`. Mit dem aktuellen Code funktioniert es wieder.

**Comment by nicpear** [comment]
Perfekt, vielen Dank! Das hat funktioniert.
