### ISSUE TITLE
No Connection / No Status

### ISSUE THREAD

**Issue by gratefulUser1** [zivillian/ora2mqtt#9]
Erst nochmal vielen Dank für deine Mühe!

Ich habe soweit einen 2. Account aufgesetzt und das Fahrzeug dort freigegeben. In der App sehe ich auch das Fahrzeug und die Daten. Konfiguration von ora2mqtt hat auch geklappt mit PIN. 

Unter Linux (arm und x64) bekomme ich immer:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at libgwmapi.GwmApiClient.GetAppAsync[T](String url, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/libgwmapi/GwmApiClient.cs:line 103
   at ora2mqtt.RunCommand.PublishStatusAsync(IMqttClient mqtt, GwmApiClient gwm, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/RunCommand.cs:line 111
   at ora2mqtt.RunCommand.Run(CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/RunCommand.cs:line 41
   at Program.<Main>$(String[] args) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/Program.cs:line 23
```

Unter Windows bekommen ich keinen Fehler, aber keine Messages im MQTT (Verbindung mit MQTT Account hat aber geklappt, wenn ich falsche Daten setze dann kommt ein anderer Fehler).

Gibt es einen Debug-/Lösungsansatz?
Ich habe leider keine Kenntnisse in C#.

**Comment by DirkRadd76** [comment]
Hallo,
unter Linux(egal welche Version) den selben Fehler wie oben beschrieben. Unter Windows funktioniert alles. Auch Mqtt!

> Erst nochmal vielen Dank für deine Mühe!
> 
> Ich habe soweit einen 2. Account aufgesetzt und das Fahrzeug dort freigegeben. In der App sehe ich auch das Fahrzeug und die Daten. Konfiguration von ora2mqtt hat auch geklappt mit PIN.
> 
> Unter Linux (arm und x64) bekomme ich immer:
> 
> ```
> System.Net.Http.HttpRequestException: An error occurred while sending the request.
> ---> System.IO.IOException: The response ended prematurely.
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at libgwmapi.GwmApiClient.GetAppAsync[T](String url, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/libgwmapi/GwmApiClient.cs:line 103
>    at ora2mqtt.RunCommand.PublishStatusAsync(IMqttClient mqtt, GwmApiClient gwm, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/RunCommand.cs:line 111
>    at ora2mqtt.RunCommand.Run(CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/RunCommand.cs:line 41
>    at Program.<Main>$(String[] args) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/Program.cs:line 23
> ```
> 
> Unter Windows bekommen ich keinen Fehler, aber keine Messages im MQTT (Verbindung mit MQTT Account hat aber geklappt, wenn ich falsche Daten setze dann kommt ein anderer Fehler).
> 
> Gibt es einen Debug-/Lösungsansatz? Ich habe leider keine Kenntnisse in C#.

Hallo,
unter Linux(egal welche Version) den selben Fehler wie oben beschrieben. Unter Windows funktioniert alles. Auch Mqtt.
Auf das richtige Topic gehört? Die Vin Nummer muss passen.

"GWM/hierdieVINNummer/status/items/2013021/value"

Aber tolle Arbeit. Wenn jetzt noch Linux läuft...

**Comment by gratefulUser1** [comment]
Ich benutze einen MQTT Server mit User Account. Unter Windows bekomme ich nach wie vor keine MQTT Messages. Habe nochmal komplett den configure Prozess neu gemacht, vorher hatte ich die YAML von Linux kopiert. @DirkRadd76 Hast du einen MQTT server mit Anmeldung? Vielleicht liegt es daran ...

Das Topic ist es denke ich nicht, ich müsste doch die Messages bekommen wenn ich auf "#" oder "GWM/#" höre oder?

**Comment by gratefulUser1** [comment]
Ich habe mit das DotNet SDK 6.0 für Linux heruntergeladen. Leider komme ich mit dem Debugging nicht wirklich voran, da ich nicht genug Ahnung habe. Kann es sein, dass der HttpClient unter Linux und Windows eine andere Standard-Konfiguration verwendet, und nur die von Windows akzeptiert wird? Hat jemand eine Idee, wie ich mir den GET request anzeigen kann, der gesendet wird?

  @zivillian: Unter welcher Linux version hast du getestet? Ich verwende Linux Mint 21.3 (Ubuntu 22.04).

**Comment by gratefulUser1** [comment]
Ich habe nochmal ein bisschen rumgespielt und folgende Zeile (26) aus der BaseCommand.cs rausgenommen:

`if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))`

Damit bekomme ich folgenden Fehler:

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A00018E:SSL routines::ca md too weak
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at libgwmapi.GwmApiClient.GetAppAsync[T](String url, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/libgwmapi/GwmApiClient.cs:line 103
   at ora2mqtt.RunCommand.PublishStatusAsync(IMqttClient mqtt, GwmApiClient gwm, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/RunCommand.cs:line 111
   at ora2mqtt.RunCommand.Run(CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/RunCommand.cs:line 41
   at Program.<Main>$(String[] args) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/Program.cs:line 23
```

Vielleicht hilft es ja weiter ...

**Comment by gratefulUser1** [comment]
OK, I just realised, the issue was already discussed here and also solved for the docker container:

https://github.com/zivillian/ora2mqtt/issues/2#issuecomment-2039021532

**I made it work using Docker on my Raspi!**

Maybe someone can point out the solutionto us using the compiled binaries w/o Docker. It seems to need some settings in the `/etc/ssl/openssl.cnf`

**Comment by DirkRadd76** [comment]
> OK, I just realised, the issue was already discussed here and also solved for the docker container:
> 
> [#2 (comment)](https://github.com/zivillian/ora2mqtt/issues/2#issuecomment-2039021532)
> 
> **I made it work using Docker on my Raspi!**
> 
> Maybe someone can point out the solution to us using the compiled binaries w/o Docker. It seems to need some settings in the `/etc/ssl/openssl.cnf`

Ich bekomme es mit Docker nicht hin.

Hast Du vielleicht eine kurze Anleitung. 

Hab mit "docker run -d --restart=unless-stopped -v ./ora2mqtt.yml:/config/ora2mqtt.yml zivillian/ora2mqtt:latest" den Container erstellt. Aber das haut irgendwie nicht hin

**Comment by gratefulUser1** [comment]
Es geht auch ohne Docker:

(bash)

`sudo cp libgwmapi/Resources/gwm_root.pem /etc/ssl/certs/`
`sudo export OPENSSL_CONF=/path/to/from/repo/openssl.cnf`

Dann das binary aus den releases ausführen.

Mit Docker musst du erst (dort wo das Dockerfile liegt):

`sudo docker build -t ora2mqtt .`

Und dann:

`docker run --rm -it -v "./ora2mqtt.yml:/config/ora2mqtt.yml" --name ora2mqtt ora2mqtt`

Wobei dein ora2mqtt.yml im aktuellen Verzeichnis liegen sollte.

**Comment by DirkRadd76** [comment]
Sorry aber ich bekomme es mit Docker nicht hin.

Wenn ich "sudo docker build -t ora2mqtt ." ausführe kommt eine Fehlermeldung.

admin@Docker:~$ ls
Dockerfile.txt  dockerfile  get-docker.sh  ora2mqtt.yml
admin@Docker:~$ sudo docker build -t ora2mqtt .
[+] Building 0.2s (15/15) FINISHED                                                                                                                                                                                                                                        docker:default
 => [internal] load build definition from dockerfile                                                                                                                                                                                                                                0.0s
 => => transferring dockerfile: 776B                                                                                                                                                                                                                                                0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine                                                                                                                                                                                                   0.1s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0                                                                                                                                                                                                                   0.1s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                     0.0s
 => [build-env 1/6] FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:3bfaf0ce4417fb6c63d9a6ac1ddde8af9684c35a2b409815dd7ce15efe3d984b                                                                                                                                                   0.0s
 => => resolve mcr.microsoft.com/dotnet/sdk:6.0@sha256:3bfaf0ce4417fb6c63d9a6ac1ddde8af9684c35a2b409815dd7ce15efe3d984b                                                                                                                                                             0.0s
 => [stage-1 1/4] FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine@sha256:0ad54e0358c6418f392d26a9518ea7d5d58ce4bcd172f4380ed213592268fe39                                                                                                                                     0.0s
 => => resolve mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine@sha256:0ad54e0358c6418f392d26a9518ea7d5d58ce4bcd172f4380ed213592268fe39                                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                     0.0s
 => CACHED [stage-1 2/4] WORKDIR /app                                                                                                                                                                                                                                               0.0s
 => CACHED [build-env 2/6] WORKDIR /app                                                                                                                                                                                                                                             0.0s
 => CACHED [build-env 3/6] COPY libgwmapi/ ./libgwmapi/                                                                                                                                                                                                                             0.0s
 => CACHED [build-env 4/6] COPY ora2mqtt/ ./ora2mqtt/                                                                                                                                                                                                                               0.0s
 => CACHED [build-env 5/6] RUN if [ "amd64" = "amd64" ]; then     RID=linux-musl-x64 ;     elif [ "amd64" = "arm64" ]; then     RID=linux-musl-arm64 ;     elif [ "amd64" = "arm" ]; then     RID=linux-musl-arm ;     fi     && dotnet publish -c Release -o out -r $RID --sc ora  0.0s
 => CACHED [build-env 6/6] COPY openssl.cnf ./out/                                                                                                                                                                                                                                  0.0s
 => CACHED [stage-1 3/4] COPY --from=build-env /app/out .                                                                                                                                                                                                                           0.0s
 => ERROR [stage-1 4/4] COPY libgwmapi/Resources/gwm_root.pem /etc/ssl/certs/.                                                                                                                                                                                                      0.0s
------
 > [stage-1 4/4] COPY libgwmapi/Resources/gwm_root.pem /etc/ssl/certs/.:
------
dockerfile:20
--------------------
  18 |     WORKDIR /app
  19 |     COPY --from=build-env /app/out .
  20 | >>> COPY libgwmapi/Resources/gwm_root.pem /etc/ssl/certs/.
  21 |     ENV OPENSSL_CONF=/app/openssl.cnf
  22 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref c2474e09-b049-4e16-a839-25cb310447c6::day288q6hx7sjt2lbhayrynpf: failed to walk /var/lib/docker/tmp/buildkit-mount3956128095/libgwmapi/Resources: lstat /var/lib/docker/tmp/buildkit-mount3956128095/libgwmapi/Resources: no such file or directory
admin@Docker:~$ 

Im Dockerfile muss doch der Code der Code rein, oder?

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY libgwmapi/ ./libgwmapi/
COPY ora2mqtt/ ./ora2mqtt/
ARG TARGETARCH
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    RID=linux-musl-x64 ; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    RID=linux-musl-arm64 ; \
    elif [ "$TARGETARCH" = "arm" ]; then \
    RID=linux-musl-arm ; \
    fi \
    && dotnet publish -c Release -o out -r $RID --sc ora2mqtt/ora2mqtt.csproj
COPY openssl.cnf ./out/

FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine
WORKDIR /app
COPY --from=build-env /app/out .
COPY libgwmapi/Resources/gwm_root.pem /etc/ssl/certs/.
ENV OPENSSL_CONF=/app/openssl.cnf

ENTRYPOINT ["/app/ora2mqtt", "-c", "/config/ora2mqtt.yml"]

Wäre cool wenn Du helfen könntest? Danke vorab!

**Comment by gratefulUser1** [comment]
Hast du das repo gecloned? Vielleicht machst du nochmal einen neuen clean
clone vom master und dann die Befehle von oben ausführen.

Aber einfacher ist, mit dem binary Release zu arbeiten wie oben beschrieben.


DirkRadd76 ***@***.***> schrieb am So., 21. Apr. 2024, 17:08:

**Comment by DirkRadd76** [comment]
> Hast du das repo gecloned? Vielleicht machst du nochmal einen neuen clean clone vom master und dann die Befehle von oben ausführen. Aber einfacher ist, mit dem binary Release zu arbeiten wie oben beschrieben. 

Hey Danke für die Hilfe aber ich kapiere nichts mehr :-)

1. Habe "docker run -d --restart=unless-stopped -v ./ora2mqtt.yml:/config/ora2mqtt.yml zivillian/ora2mqtt:latest" auf meiner Docker Umgebung ausgeführt. Der Container wurde angelegt. Steht zumindest so auf der Portainer Webseite
2.  Dann ein Dockerfile mit dem Code von Seite angelegt. Keine Ahnung ob das so geht/richtig war.
3. Dann "sudo docker build -t ora2mqtt ."---> Mit Fehlermeldung

Bin nicht so der Linuxexperte....

Aber mach dir keine Mühe und Danke für die Hilfe bis hier.

**Comment by gratefulUser1** [comment]
Ich denke du brauchst das ganze Repo! Das bekommst du mit git clone. Dort ist schon das Dockerfile dabei. Eben bei mir nochmal folgende Schritte getestet, es läuft. Erstelle eine neues Verzeichnis und wechsle dahin. Dann:

```
git clone https://github.com/zivillian/ora2mqtt.git
cd ora2mqtt/
sudo docker build -t ora2mqtt .
cp /path/to/existing/ora2mqtt.yml .
sudo docker run --rm -it -v "./ora2mqtt.yml:/config/ora2mqtt.yml" --name ora2mqtt ora2mqtt
```

Läuft einwandfrei.

**Comment by DirkRadd76** [comment]
Vielen Dank!!!!!!

Mit der Anleitung läuft es!!!

> Ich denke du brauchst das ganze Repo! Das bekommst du mit git clone. Dort ist schon das Dockerfile dabei. Eben bei mir nochmal folgende Schritte getestet, es läuft. Erstelle eine neues Verzeichnis und wechsle dahin. Dann:
> 
> ```
> git clone https://github.com/zivillian/ora2mqtt.git
> cd ora2mqtt/
> sudo docker build -t ora2mqtt .
> cp /path/to/existing/ora2mqtt.yml .
> sudo docker run --rm -it -v "./ora2mqtt.yml:/config/ora2mqtt.yml" --name ora2mqtt ora2mqtt
> ```
> 
> Läuft einwandfrei.

Vielen Dank!!!!!!

Mit der Anleitung läuft es als Docker!!! Sauber!!

Bist eigentlich zufrieden mit der Katze? Kann bis jetzt nicht meckern. PV Überschussladen läuft auch gut. Und jetzt noch besser ;-)

Gruß Dirk und nochmals vielen Dank

**Comment by gratefulUser1** [comment]
Alles klar, hoffe das es vielen helfen kann :-)

Insgesamt sind wir schon zufrieden, bis auf Kleinigkeiten z.B. die
unnötigen Sounds/Töne die man nicht abstellen kann, oder die
Notlenkfunktion die sich jedes mal wieder einstellt ...

VG

DirkRadd76 ***@***.***> schrieb am So., 21. Apr. 2024, 18:03:
